Repository Java-and-Script/pickple-back, pull requests merged in 2023-12, with the labels that each got.

#256 [#125] 게스트 모집글 관련 docs 테스트 추가
  src/test/java/kr/pickple/back/game/docs/GameDocumentTest.java
Labels: 테스트

#268 [#267]fix: accessToken 완료 시간(6시간) 시 sse 연결이 끊기는 문제
  src/main/java/kr/pickple/back/alarm/controller/AlarmController.java
  src/main/java/kr/pickple/back/alarm/repository/RedisEventCacheRepository.java
  src/main/java/kr/pickple/back/alarm/service/SseEmitterService.java
  src/main/java/kr/pickple/back/auth/controller/OauthController.java
Labels: 버그

#275 [#274] refactor: 알람 관련 미사용 sseEmitter 메소드 삭제
  src/main/java/kr/pickple/back/alarm/controller/AlarmController.java
  src/main/java/kr/pickple/back/alarm/repository/SseEmitterLocalRepository.java
  src/main/java/kr/pickple/back/alarm/repository/SseEmitterRepository.java
  src/main/java/kr/pickple/back/alarm/service/SseEmitterService.java
Labels: 리팩토링
