Repository Java-and-Script/pickple-back, pull requests merged in 2023-11, with the labels that each got.

#39 [#38] 사용자 프로필 조회 기능 추가
  src/main/http/member/member.http
  src/main/java/kr/pickple/back/crew/dto/response/CrewResponse.java
  src/main/java/kr/pickple/back/member/controller/MemberController.java
  src/main/java/kr/pickple/back/member/domain/MemberPosition.java
  src/main/java/kr/pickple/back/member/dto/response/MemberProfileResponse.java
  src/main/java/kr/pickple/back/member/dto/response/MemberResponse.java
  src/main/java/kr/pickple/back/member/repository/MemberPositionRepository.java
  src/main/java/kr/pickple/back/member/service/MemberService.java
Labels: 신규 기능

#45 [#44] OAuth, JWT 관련 기능 리팩토링
  src/main/java/kr/pickple/back/auth/config/AuthConfig.java
  src/main/java/kr/pickple/back/auth/config/http/KakaoAuthHttpInterfaceConfig.java
  src/main/java/kr/pickple/back/auth/config/http/KakaoMemberHttpInterfaceConfig.java
  src/main/java/kr/pickple/back/auth/config/property/KakaoOauthProperties.java
  src/main/java/kr/pickple/back/auth/controller/OauthController.java
  src/main/java/kr/pickple/back/auth/domain/oauth/OAuthProvider.java
  src/main/java/kr/pickple/back/auth/domain/oauth/OauthMember.java
  src/main/java/kr/pickple/back/auth/domain/oauth/OauthProvider.java
  src/main/java/kr/pickple/back/auth/domain/token/JwtProvider.java
  src/main/java/kr/pickple/back/auth/dto/kakao/KakaoMemberResponse.java
  src/main/java/kr/pickple/back/auth/dto/kakao/KakaoTokenResponse.java
  src/main/java/kr/pickple/back/auth/service/OAuthService.java
  src/main/java/kr/pickple/back/auth/service/OauthService.java
  src/main/java/kr/pickple/back/auth/service/authcode/AuthCodeRequestUrlProvider.java
  src/main/java/kr/pickple/back/auth/service/authcode/AuthCodeRequestUrlProviderComposite.java
  src/main/java/kr/pickple/back/auth/service/authcode/KakaoAuthCodeRequestUrlProvider.java
  src/main/java/kr/pickple/back/auth/service/memberclient/KakaoMemberClient.java
  src/main/java/kr/pickple/back/auth/service/memberclient/OAuthMemberClient.java
  src/main/java/kr/pickple/back/auth/service/memberclient/OAuthMemberClientComposite.java
  src/main/java/kr/pickple/back/auth/service/memberclient/OauthMemberClient.java
  src/main/java/kr/pickple/back/auth/service/memberclient/OauthMemberClientComposite.java
  src/main/java/kr/pickple/back/auth/util/OAuthProviderConverter.java
  src/main/java/kr/pickple/back/auth/util/OauthProviderConverter.java
  src/main/java/kr/pickple/back/common/config/WebConfig.java
  src/main/java/kr/pickple/back/member/domain/Member.java
  src/main/java/kr/pickple/back/member/dto/request/MemberCreateRequest.java
  src/main/java/kr/pickple/back/member/dto/response/AuthenticatedMemberResponse.java
Labels: 리팩토링

#53 [#40] 크루 상세 조회 기능 구현
  src/main/http/crew/crew.http
  src/main/java/kr/pickple/back/crew/controller/CrewController.java
  src/main/java/kr/pickple/back/crew/dto/response/CrewProfileResponse.java
  src/main/java/kr/pickple/back/crew/service/CrewService.java
Labels: 신규 기능

#86 [#83] 크루원 가입 삭제/취소 실행 구현
  src/main/http/crew/crew.http
  src/main/java/kr/pickple/back/crew/exception/CrewExceptionCode.java
  src/main/java/kr/pickple/back/crew/repository/CrewMemberRepository.java
  src/main/java/kr/pickple/back/crew/service/CrewMemberService.java
Labels: 신규 기능

#10 [#7] Sonar Cloud,Jacoco 설정 추가
  .github/workflows/ci-pr.yml
  .github/workflows/ci-push.yml
  README.md
  build.gradle
Labels: 빌드, 기타

#99 [#97] MemberProfileResponse에서 Crews에 대한 부분 채우기
  src/main/java/kr/pickple/back/crew/dto/response/CrewProfileResponse.java
  src/main/java/kr/pickple/back/crew/dto/response/CrewResponse.java
  src/main/java/kr/pickple/back/crew/service/CrewMemberService.java
  src/main/java/kr/pickple/back/crew/service/CrewService.java
  src/main/java/kr/pickple/back/member/domain/Member.java
  src/main/java/kr/pickple/back/member/domain/MemberCrews.java
  src/main/java/kr/pickple/back/member/dto/response/MemberProfileResponse.java
  src/main/java/kr/pickple/back/member/service/MemberService.java
  src/test/java/kr/pickple/back/member/docs/MemberDocumentTest.java
Labels: 리팩토링

#101 [#100] 인증, 인가 로직 AccessToken만 검증하는 것으로 변경 처리
  src/main/java/kr/pickple/back/auth/config/resolver/LoginTokenArgumentResolver.java
  src/main/java/kr/pickple/back/auth/domain/token/JwtProvider.java
Labels: 신규 기능

#103 [#102] 사용자 프로필 조회 시 대기 상태의 크루 목록 보이는 버그 해결
  src/main/java/kr/pickple/back/member/domain/Member.java
  src/main/java/kr/pickple/back/member/domain/MemberCrews.java
  src/main/java/kr/pickple/back/member/service/MemberService.java
Labels: 버그

#142 [#141] 사용자 근처 크루 목록 조회에서 인증 로직 제거
  src/main/http/crew/crew.http
  src/main/java/kr/pickple/back/crew/controller/CrewController.java
  src/main/java/kr/pickple/back/crew/service/CrewService.java
Labels: 버그

#149 [#148] RequestMapping 경로 겹치는 현상 문제 해결
  src/main/java/kr/pickple/back/game/controller/GameController.java
Labels: 버그

#162 [#160] 위치수집 동의를 하지 않은 사용자에게 특정 지역의 게스트 모집글을 보여주는 기능
  src/main/java/kr/pickple/back/game/controller/GameController.java
  src/main/java/kr/pickple/back/game/domain/GameMembers.java
  src/main/java/kr/pickple/back/game/repository/GameSearchRepository.java
  src/main/java/kr/pickple/back/game/repository/GameSearchRepositoryImpl.java
  src/main/java/kr/pickple/back/game/service/GameService.java
  src/main/java/kr/pickple/back/map/domain/MapPolygon.java
Labels: 신규 기능

#172 [#170] prod-cd 스크립트 오류 수정
  .github/workflows/prod-cd.yml
Labels: 빌드, 버그

#178 [#177] prod-cd 스크립트 오류 수정
  .github/workflows/prod-cd.yml
Labels: 배포

#183 [#182] 로그아웃 기능 구현
  src/main/java/kr/pickple/back/auth/controller/OauthController.java
  src/main/java/kr/pickple/back/auth/domain/token/JwtProvider.java
  src/main/java/kr/pickple/back/auth/service/OauthService.java
Labels: 신규 기능

#188 [#187] 채팅방 나가기 이후, 채팅방 목록 조회 시 사라지지 않는 현상 해결
  src/main/java/kr/pickple/back/chat/controller/ChatRoomController.java
  src/main/java/kr/pickple/back/chat/repository/ChatRoomMemberRepository.java
  src/main/java/kr/pickple/back/chat/service/ChatRoomFindService.java
Labels: 버그

#186 [#116] 게스트 모집 컨트롤러 통합 테스트 코드 작성
  src/test/java/kr/pickple/back/game/controller/GameControllerTest.java
Labels: 테스트

#195 [#194] 크루 생성 개수 초과 예외 적용
  src/main/java/kr/pickple/back/crew/exception/CrewExceptionCode.java
  src/main/java/kr/pickple/back/crew/service/CrewService.java
  src/main/java/kr/pickple/back/member/domain/Member.java
  src/main/java/kr/pickple/back/member/domain/MemberCrews.java
Labels: 버그

#199 [#198] 로그아웃시 RefreshToken이 사라지지 않는 현상 해결
  src/main/java/kr/pickple/back/auth/controller/OauthController.java
Labels: 버그

#202 [#201] 자기소개, 상세설명 기본값 추가 및 nullable로 변경
  src/main/java/kr/pickple/back/crew/domain/Crew.java
  src/main/java/kr/pickple/back/game/domain/Game.java
  src/main/java/kr/pickple/back/member/domain/Member.java
Labels: 신규 기능

#205 [#204] 특정 사용자와의 1:1 채팅방 조회 API의 응답값 변경
  src/main/http/chat/chat.http
  src/main/java/kr/pickple/back/chat/controller/ChatRoomController.java
  src/main/java/kr/pickple/back/chat/dto/response/PersonalChatRoomExistedResponse.java
  src/main/java/kr/pickple/back/chat/service/ChatRoomService.java
Labels: 버그

#208 [#207] 통합테스트 속도 개선
  src/test/java/kr/pickple/back/auth/IntegrationAuthTest.java
  src/test/java/kr/pickple/back/auth/controller/AuthControllerTest.java
  src/test/java/kr/pickple/back/auth/docs/AuthDocumentTest.java
  src/test/java/kr/pickple/back/auth/domain/JwtProviderTest.java
  src/test/java/kr/pickple/back/game/IntegrationGameTest.java
  src/test/java/kr/pickple/back/game/controller/GameControllerTest.java
  src/test/java/kr/pickple/back/game/docs/GameDocumentTest.java
  src/test/java/kr/pickple/back/member/IntegrationMemberTest.java
  src/test/java/kr/pickple/back/member/controller/MemberControllerTest.java
  src/test/java/kr/pickple/back/member/docs/MemberDocumentTest.java
Labels: 테스트

#238 [#237] 실시간 크루 알람, 게임 알람 메시지가 오지 않는 에러 수정
  src/main/java/kr/pickple/back/alarm/repository/SseEmitterLocalRepository.java
  src/main/java/kr/pickple/back/alarm/repository/SseEmitterRepository.java
  src/main/java/kr/pickple/back/alarm/service/SseEmitterService.java
Labels: 버그

#231 [#230] 조건별(장소, 날짜, 포지션별) 게스트 모집글 조회 기능에서 종료된 경기는 조회되지 않도록 수정
  src/main/java/kr/pickple/back/game/domain/Game.java
  src/main/java/kr/pickple/back/game/service/GameService.java
Labels: 버그

#248 [#247] 지도에서 종료된 게스트 모집글을 불러오는 현상 해결
  src/main/java/kr/pickple/back/game/service/GameService.java
Labels: 버그
